apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 289052325869.dkr.ecr.us-east-1.amazonaws.com/assignment2-dev-ecr:my_db
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: mysql-root-password
  imagePullSecrets:
    - name: ecr-secret
