apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  imagePullSecrets:
  - name: ecr-secret
  containers:
  - name: web-app
    image: 289052325869.dkr.ecr.us-east-1.amazonaws.com/assignment2-dev-ecr:my_app
    ports:
    - containerPort: 80
    env:
    - name: DBHOST
      value: "mysql"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"
    - name: APP_COLOR
      value: "green"