apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: employees
spec:
  containers:
    - name: web-app
      image: 289052325869.dkr.ecr.us-east-1.amazonaws.com/assignment2-dev-ecr:my_app
      ports:
        - containerPort: 80
