apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: web-app
          image: <ECR_URI>:<tag>
          ports:
            - containerPort: 80
